-- File: FourToSeven.vhd
-- Generated by MyHDL 0.8dev
-- Date: Sun Mar 24 12:48:54 2013


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_08.all;

entity FourToSeven is
    port (
        ByteIn: in unsigned(3 downto 0);
        Enable: in std_logic;
        Polarity: in std_logic;
        SegOut: out unsigned(6 downto 0)
    );
end entity FourToSeven;


architecture MyHDL of FourToSeven is


begin




FOURTOSEVEN_COMB: process (Polarity, ByteIn, Enable) is
    variable SegBuf: unsigned(6 downto 0);
begin
    SegBuf := to_unsigned(0, 7);
    if (Enable = '1') then
        case to_integer(ByteIn) is
            when 0 => SegBuf := "0111111";
            when 1 => SegBuf := "0000110";
            when 2 => SegBuf := "1011011";
            when 3 => SegBuf := "1001111";
            when 4 => SegBuf := "1100110";
            when 5 => SegBuf := "1101101";
            when 6 => SegBuf := "1111101";
            when 7 => SegBuf := "0000111";
            when 8 => SegBuf := "1111111";
            when 9 => SegBuf := "1101111";
            when 10 => SegBuf := "1110111";
            when 11 => SegBuf := "1111100";
            when 12 => SegBuf := "0111001";
            when 13 => SegBuf := "1011110";
            when 14 => SegBuf := "1111001";
            when others => SegBuf := "1110001";
        end case;
    end if;
    if (Polarity = '0') then
        SegBuf := (not SegBuf);
    end if;
    SegOut <= SegBuf;
end process FOURTOSEVEN_COMB;

end architecture MyHDL;
